### ISSUE TITLE
Jetbrains RITA Plugin not compatible with PyCharm 2020.2.1

### ISSUE THREAD

**Issue by rolandmueller** [zaibacu/rita-dsl#100]
Plugin Version: 1.2
https://plugins.jetbrains.com/plugin/15011-rita-language/versions/

Tested Version:
PyCharm 2020.2.1 (Professional Edition)

Error when trying to install from disk:
<img width="400" alt="grafik" src="https://user-images.githubusercontent.com/459179/93174662-a65eac00-f72e-11ea-9344-655aeb407c32.png">

On the plugin site https://plugins.jetbrains.com/plugin/15011-rita-language/versions/ it says, that this should be uncompitable for all IntellJ-based IDEs in the 2020.2 version:
 

> The list of supported products was determined by dependencies defined in the plugin.xml: 
> Android Studio — build 201.7223 — 201.*
> DataGrip — 2020.1.3 — 2020.1.5
> IntelliJ IDEA Ultimate — 2020.1.1 — 2020.1.4
> Rider — 2020.1.3
> PyCharm Professional — 2020.1.1 — 2020.1.4
> PyCharm Community — 2020.1.1 — 2020.1.4
> PhpStorm — 2020.1.1 — 2020.1.4
> IntelliJ IDEA Educational — 2020.1.1 — 2020.1.2
> CLion — 2020.1.1 — 2020.1.3
> PyCharm Educational — 2020.1.1 — 2020.1.2
> GoLand — 2020.1.1 — 2020.1.4
> AppCode — 2020.1.2 — 2020.1.6
> RubyMine — 2020.1.1 — 2020.1.4
> MPS — 2020.1.1 — 2020.1.4
> IntelliJ IDEA Community — 2020.1.1 — 2020.1.4
> WebStorm — 2020.1.1 — 2020.1.4

**Comment by zaibacu** [comment]
Thank you for report! will look into it

**Comment by zaibacu** [comment]
Ok, so it turns out, that Idea plugins has a bit weird compatibility policy... :) managed to include `2020.1-2020.2` versions. Should be fine in version `1.3` (Tested on Pycharm 2020.2 Community and IntelijJ 2020.1 Community)

However, it takes several days for them to manually approve plugin. 
You can download it manually from [Here](https://plugins.jetbrains.com/plugin/download?rel=true&updateId=96986) and manually copy to [plugins directory](https://www.jetbrains.com/help/pycharm/directories-used-by-the-ide-to-store-settings-caches-plugins-and-logs.html#logs-directory) to test it before approval

**Comment by rolandmueller** [comment]
I tested it and it works now. Thank you! 
Very nice plugin by the way.
